name: 'Setup Java Environment'
description: 'Sets up JDK 25 with Temurin distribution and Maven caching'

runs:
  using: composite
  steps:
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
